apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: njs06afdh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: njs06afdh-nodejs 
  name: njs06afdh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: njs06afdh-nodejs 
